# ตั้งค่าเชื่อมต่อ MySQL (สร้าง Database ชื่อ performance_db ให้อัตโนมัติ)
spring.datasource.url=mysql://avnadmin:AVNS_hr4WIwQZghN5owOmtlC@mysql-6e51c7c-performancetracking.l.aivencloud.com:21161/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_hr4WIwQZghN5owOmtlC

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect